name: csir_soil_sensor
description: "Flutter app for ESP32 NPK soil sensor with local storage and export."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  flutter_blue_plus: ^1.34.5
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  share_plus: ^10.1.2
  csv: ^6.0.0
  pdf: ^3.11.0
  printing: ^5.13.3
  drift: ^2.18.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/
